### ISSUE TITLE
Support for TLS-protected Vault connections

### ISSUE THREAD

**Issue by jeremypruitt** [tuenti/pouch#10]
Any thoughts on what it would take to support TLS-protected Vault connections? I tried passing the VAULT_CACERT, VAULT_CLIENT_CERT. and VAULT_CLIENT_KEY variables, but I continued to received the following message from Pouch:
```
Couldn't obtain secret ID from /tmp/vault-wrapped-secret-id: no response?
```
and the following message in the Vault server log:
```
remote error: tls: bad certificate
```
These same certs allow me to run things like ```vault status``` successfully.

I'm happy to help phrase this in the form of a pull request, but thought I would reach out before digging in to first make sure it's not operator error on my part and that you would want a PR.

**Comment by jsoriano** [comment]
@jeremypruitt my apologies for so late reply.

The truth is that we haven't tested pouch with self-signed certificates, so it's very possible that it isn't working. If you are still interested in doing it, it'd be great if you could help to confirm the issue and prepare a PR for this. Thanks for your interest!

**Comment by jsoriano** [comment]
I think the fix would be to call to `config.ReadEnvironment()` after obtaining the `DefaultConfig()`.

**Comment by fcgravalos** [comment]
Hi @jeremypruitt , thanks for using Pouch!

Let me know if we understand the issue you're running into. 

If you just want to use self-signed certs as part of your tls config, you need to start vault with a configuration similar to this one (the storage should differ, just checkout the listener section):

```
storage "inmem" {}
listener "tcp" {
  address = "vault.example.com:8200"
  tls_cert_file="<path_to_my_ca.pem>"
  tls_key_file="<path_to_my_ca.key>"
}
``` 

And make sure you either install your cert, or skip the tls validation, in which case you need to set `VAULT_SKIP_VERIFY` to true:

`export VAULT_SKIP_VERIFY=true` 

In the meantime a this [PR](https://github.com/tuenti/pouch/pull/16) has been created to support Vault built-in environment variables.

On the other hand, if you're goal is to authenticate Pouch using Vault tls method, that's not the goal of Pouch though. Pouch aims to authenticate apps not individuals, we may consider supporting other authentication methods to Vault, but for now we just want to focus on improving the current one.

BR
